'use client'

import { useState, useEffect, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { format, addDays, parseISO } from 'date-fns'
import { Pencil, Loader2, ArrowRight } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { useStore } from '@/lib/store/useStore'
import { useJournal } from '@/hooks/useJournal'
import { JournalInput } from '@/components/journal/JournalInput'
import { ParsedEntryView } from '@/components/journal/ParsedEntryView'
import { OnboardingFlow } from '@/components/onboarding/OnboardingFlow'
import { NameSetup } from '@/components/onboarding/NameSetup'
import { GoalsSetup } from '@/components/onboarding/GoalsSetup'
import type { DailyLog, ParsedEntry, MentalState } from '@/lib/types'

interface TodayClientProps {
  userId: string
  currentLogDate: string
  /** Name from profile — null if not yet set / looks auto-generated */
  profileName: string | null
  email: string
  /** Onboarding flags from profiles table — DB is source of truth */
  nameSet: boolean
  goalsSet: boolean
  onboardingComplete: boolean
}

type OnboardingStep = 'idle' | 'name' | 'goals' | 'onboarding'

function getGreeting(name: string): string {
  const hour = new Date().getHours()
  let timeGreeting: string
  if (hour >= 5 && hour < 12) timeGreeting = 'Good morning'
  else if (hour >= 12 && hour < 17) timeGreeting = 'Good afternoon'
  else if (hour >= 17 && hour < 21) timeGreeting = 'Good evening'
  else timeGreeting = 'Good night'
  return `${timeGreeting}, ${name}`
}

/** Returns true if the name looks auto-generated from an email (e.g. "jashfiji14") */
function looksAutoGenerated(name: string | null): boolean {
  if (!name) return true
  return /\d/.test(name) || (name.length > 0 && !/\s/.test(name) && name.length > 12)
}

function getRatingColor(v: number): string {
  if (v <= 3) return '#F87171'
  if (v <= 6) return '#FBBF24'
  return '#4ADE80'
}

export function TodayClient({ userId, currentLogDate, profileName, email, nameSet, goalsSet, onboardingComplete }: TodayClientProps) {
  const router = useRouter()
  const { analyseEntry, analysing, error: analyseError } = useJournal()
  const { currentName, setCurrentName } = useStore()

  // Seed the store from the server-fetched profile name on every mount.
  // profileName comes from profiles.name — always prefer it over anything
  // already in the store, which may be a stale email-derived value.
  // NameSetup also writes here directly so the greeting updates immediately.
  useEffect(() => {
    setCurrentName(profileName ?? email.split('@')[0])
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const [greeting, setGreeting] = useState(() =>
    getGreeting(currentName ?? profileName ?? email.split('@')[0])
  )
  const [onboardingStep, setOnboardingStep] = useState<OnboardingStep>('idle')

  function postOnboardingFlag(flag: 'name_set' | 'goals_set' | 'onboarding_complete') {
    fetch('/api/onboarding/set-flag', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ flag, value: true }),
    }).catch(console.error)
  }

  const [log, setLog] = useState<DailyLog | null>(null)
  const [entries, setEntries] = useState<ParsedEntry[]>([])
  const [mentalState, setMentalState] = useState<MentalState | null>(null)
  const [wellbeingInsight, setWellbeingInsight] = useState<string | null>(null)
  const [flagged, setFlagged] = useState(false)
  const [crisisDismissed, setCrisisDismissed] = useState(false)
  const [editing, setEditing] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [showNewDayModal, setShowNewDayModal] = useState(false)
  const [startingNewDay, setStartingNewDay] = useState(false)

  interface HabitNudge { id: string; habit_id: string; habit_name: string }
  const [nudges, setNudges] = useState<HabitNudge[]>([])

  // Decide onboarding step on mount.
  // Props (from profiles table) are the source of truth — they work on
  // any device even with a cold localStorage. Seed localStorage from props
  // so within-session transitions that still read localStorage stay correct.
  useEffect(() => {
    if (nameSet) localStorage.setItem('stride_name_set', '1')
    if (goalsSet) localStorage.setItem('stride_goals_set', 'true')
    if (onboardingComplete) localStorage.setItem('stride_onboarding_complete', '1')

    const effectiveNameSet = nameSet || !!localStorage.getItem('stride_name_set')
    const effectiveGoalsSet = goalsSet || !!localStorage.getItem('stride_goals_set')
    const effectiveOnboardingDone = onboardingComplete || !!localStorage.getItem('stride_onboarding_complete')

    if (!effectiveNameSet && looksAutoGenerated(profileName)) {
      setOnboardingStep('name')
    } else if (!effectiveGoalsSet) {
      setOnboardingStep('goals')
    } else if (!effectiveOnboardingDone) {
      setOnboardingStep('onboarding')
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profileName])

  // Re-compute greeting whenever the name in the store changes (NameSetup writes here)
  // or when the clock crosses a time boundary (checked every minute)
  useEffect(() => {
    const name = currentName ?? profileName ?? email.split('@')[0]
    const tick = () => setGreeting(getGreeting(name))
    tick()
    const id = setInterval(tick, 60_000)
    return () => clearInterval(id)
  }, [currentName, profileName, email])

  // Fetch habit nudges for habits with a 7+ streak that weren't logged today
  useEffect(() => {
    async function fetchNudges() {
      const supabase = createClient()
      const yesterday = format(addDays(parseISO(currentLogDate), -1), 'yyyy-MM-dd')

      // Future habits with streak >= 7 that were last detected yesterday (at risk today)
      const { data: atRiskHabits } = await supabase
        .from('future_habits')
        .select('id, habit_name')
        .eq('user_id', userId)
        .gte('current_streak', 7)
        .eq('last_detected', yesterday)

      if (!atRiskHabits || atRiskHabits.length === 0) return

      // Upsert nudge records for today
      const nudgeRows = atRiskHabits.map((h: { id: string }) => ({
        habit_id: h.id,
        user_id: userId,
        nudge_date: currentLogDate,
        dismissed: false,
      }))

      await supabase
        .from('habit_nudges')
        .upsert(nudgeRows, { onConflict: 'habit_id,nudge_date', ignoreDuplicates: true })

      // Fetch today's undismissed nudges (join future_habits to get habit_name via FK)
      const { data: todayNudges } = await supabase
        .from('habit_nudges')
        .select('id, habit_id, future_habits(habit_name)')
        .eq('user_id', userId)
        .eq('nudge_date', currentLogDate)
        .eq('dismissed', false)

      if (todayNudges) {
        setNudges(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          todayNudges.map((n: any) => ({
            id: n.id as string,
            habit_id: n.habit_id as string,
            habit_name: (Array.isArray(n.future_habits) ? n.future_habits[0]?.habit_name : n.future_habits?.habit_name) ?? '',
          }))
        )
      }
    }

    fetchNudges().catch(console.error)
  }, [userId, currentLogDate])

  async function dismissNudge(nudgeId: string) {
    const supabase = createClient()
    await supabase.from('habit_nudges').update({ dismissed: true }).eq('id', nudgeId)
    setNudges((prev) => prev.filter((n) => n.id !== nudgeId))
  }

  // Fetch today's log whenever the authoritative date changes
  useEffect(() => {
    setIsLoading(true)
    setLog(null)
    setEntries([])
    setMentalState(null)
    setWellbeingInsight(null)
    setFlagged(false)
    setCrisisDismissed(false)
    setEditing(false)

    async function fetchTodayLog() {
      const supabase = createClient()

      const { data: todayLog } = await supabase
        .from('daily_logs')
        .select('*')
        .eq('user_id', userId)
        .eq('log_date', currentLogDate)
        .single()

      if (todayLog?.ai_parsed) {
        const [{ data: parsedEntries }, { data: ms }] = await Promise.all([
          supabase
            .from('parsed_entries')
            .select('*')
            .eq('daily_log_id', todayLog.id)
            .order('created_at', { ascending: true }),
          supabase
            .from('mental_states')
            .select('*')
            .eq('daily_log_id', todayLog.id)
            .single(),
        ])
        setEntries((parsedEntries as ParsedEntry[]) ?? [])
        setMentalState(ms as MentalState | null)
      }

      setLog((todayLog as DailyLog) ?? null)
      setIsLoading(false)
    }

    fetchTodayLog()
  }, [userId, currentLogDate])

  const dateLabel = currentLogDate
    ? format(parseISO(currentLogDate), 'EEEE, MMMM d')
    : ''

  const handleNameComplete = useCallback((_name: string) => {
    // Store was already updated in NameSetup before onComplete was called.
    // The greeting effect will fire on its own from the store change.
    postOnboardingFlag('name_set')
    const currentGoalsSet = localStorage.getItem('stride_goals_set')
    setOnboardingStep(currentGoalsSet ? 'onboarding' : 'goals')
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleNameSkip = useCallback(() => {
    // Don't mark as permanently set — ask again next time. No DB call on skip.
    const currentGoalsSet = localStorage.getItem('stride_goals_set')
    setOnboardingStep(currentGoalsSet ? 'onboarding' : 'goals')
  }, [])

  const handleGoalsComplete = useCallback(() => {
    postOnboardingFlag('goals_set')
    setOnboardingStep('onboarding')
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleOnboardingComplete = useCallback(() => {
    postOnboardingFlag('onboarding_complete')
    setOnboardingStep('idle')
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleSaved = useCallback((savedLog: DailyLog) => {
    setLog(savedLog)
    setEntries([])
    setMentalState(null)
    setWellbeingInsight(null)
    setFlagged(false)
    setCrisisDismissed(false)
    setEditing(false)
  }, [])

  const handleAnalyse = useCallback(async () => {
    if (!log) return
    const result = await analyseEntry(log.id, log.raw_text, currentLogDate)
    if (!result) return
    setEntries(result.entries)
    setMentalState(result.mental_state)
    setWellbeingInsight(result.wellbeing_insight)
    setFlagged(result.flagged)
    setCrisisDismissed(false)
    setLog((prev) => (prev ? { ...prev, ai_parsed: true } : prev))
  }, [log, currentLogDate, analyseEntry])

  const handleConfirmNewDay = useCallback(async () => {
    setStartingNewDay(true)
    try {
      const supabase = createClient()
      const nextDate = format(addDays(parseISO(currentLogDate), 1), 'yyyy-MM-dd')
      await supabase
        .from('profiles')
        .update({ current_log_date: nextDate })
        .eq('id', userId)
      setShowNewDayModal(false)
      router.refresh()
    } finally {
      setStartingNewDay(false)
    }
  }, [currentLogDate, userId, router])

  const view = isLoading
    ? 'loading'
    : !log || editing
    ? 'input'
    : log.ai_parsed
    ? 'analysed'
    : 'saved'

  const hasEntry = !!log && !editing

  return (
    <>
      {/* ── Onboarding overlay ─────────────────────────────────────────── */}
      <AnimatePresence>
        {onboardingStep === 'name' && (
          <NameSetup
            userId={userId}
            onComplete={handleNameComplete}
            onSkip={handleNameSkip}
          />
        )}
        {onboardingStep === 'goals' && (
          <GoalsSetup userId={userId} onComplete={handleGoalsComplete} />
        )}
        {onboardingStep === 'onboarding' && (
          <OnboardingFlow onComplete={handleOnboardingComplete} />
        )}
      </AnimatePresence>

      <div className="mx-auto max-w-2xl px-4 py-6">
        {/* Nudge banners */}
        <AnimatePresence>
          {nudges.map((nudge) => (
            <motion.div
              key={nudge.id}
              initial={{ opacity: 0, y: -6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, height: 0, marginBottom: 0 }}
              transition={{ duration: 0.2 }}
              className="mb-3 flex items-center justify-between gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/10 px-4 py-3"
            >
              <p className="text-sm text-amber-400">
                🔥 Keep your <span className="font-medium capitalize">{nudge.habit_name}</span> streak alive — don&apos;t forget today
              </p>
              <button
                onClick={() => dismissNudge(nudge.id)}
                className="shrink-0 text-xs text-amber-400/70 hover:text-amber-400"
              >
                ✕
              </button>
            </motion.div>
          ))}
        </AnimatePresence>

        {/* Header */}
        <div className="mb-6">
          <p className="text-sm text-[var(--text-muted)]">{greeting}</p>
          <h1 className="mt-0.5 text-2xl font-semibold text-[var(--text-primary)]">
            {dateLabel}
          </h1>
        </div>

        <AnimatePresence mode="wait">
          {/* ── Loading ──────────────────────────────────────────────────── */}
          {view === 'loading' && (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-4"
            >
              <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5">
                <div className="h-[200px] animate-pulse rounded-xl bg-[var(--card-elevated)]" />
              </div>
              <div className="h-14 animate-pulse rounded-2xl bg-[var(--card-elevated)]" />
            </motion.div>
          )}

          {/* ── State 1: No entry / editing ──────────────────────────────── */}
          {view === 'input' && (
            <motion.div
              key="input"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.25 }}
            >
              <JournalInput
                logDate={currentLogDate}
                existingLog={editing ? log : null}
                onSaved={handleSaved}
              />
            </motion.div>
          )}

          {/* ── State 2: Saved, not yet analysed ─────────────────────────── */}
          {view === 'saved' && log && (
            <motion.div
              key="saved"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.25 }}
              className="space-y-5"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  {log.mood_emoji && (
                    <span className="text-3xl">{log.mood_emoji}</span>
                  )}
                  <div>
                    {log.self_rating && (
                      <span
                        className="text-2xl font-bold"
                        style={{ color: getRatingColor(log.self_rating) }}
                      >
                        {log.self_rating}
                        <span className="text-sm font-normal text-[var(--text-muted)]">
                          /10
                        </span>
                      </span>
                    )}
                    {log.weight_kg && (
                      <p className="text-xs text-[var(--text-muted)]">
                        {log.weight_kg} kg
                      </p>
                    )}
                  </div>
                </div>
                <button
                  onClick={() => setEditing(true)}
                  className="flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--card-elevated)] px-3 py-2 text-xs font-medium text-[var(--text-secondary)] transition-colors hover:text-[var(--text-primary)]"
                >
                  <Pencil size={13} />
                  Edit
                </button>
              </div>

              <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5">
                <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-[var(--text-secondary)]">
                  {log.raw_text}
                </pre>
              </div>

              {analyseError && (
                <p className="rounded-xl bg-[var(--negative)]/10 px-4 py-2 text-sm text-[var(--negative)]">
                  {analyseError}
                </p>
              )}

              <motion.button
                onClick={handleAnalyse}
                disabled={analysing}
                whileTap={{ scale: 0.97 }}
                className="w-full overflow-hidden rounded-2xl bg-[var(--accent)] py-4 text-base font-semibold text-white transition-opacity disabled:opacity-60"
              >
                {analysing ? (
                  <span className="flex items-center justify-center gap-2">
                    <Loader2 size={18} className="animate-spin" />
                    Analysing your wellbeing…
                  </span>
                ) : (
                  '✨ Analyse My Wellbeing'
                )}
              </motion.button>

              {!analysing && (
                <p className="text-center text-xs text-[var(--text-muted)]">
                  Get AI insights about your day
                </p>
              )}
            </motion.div>
          )}

          {/* ── State 3: Saved + analysed ─────────────────────────────────── */}
          {view === 'analysed' && log && (
            <motion.div
              key="analysed"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="space-y-4"
            >
              {/* Crisis resources banner — shown when flagged, dismissible */}
              <AnimatePresence>
                {flagged && !crisisDismissed && (
                  <motion.div
                    initial={{ opacity: 0, y: -6 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, height: 0, marginBottom: 0 }}
                    transition={{ duration: 0.25 }}
                    className="rounded-2xl border border-amber-500/40 bg-amber-500/10 px-4 py-4"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-amber-300">
                          We noticed some signals in your entry that suggest you might be going through a difficult time. You&apos;re not alone.
                        </p>
                        <p className="mt-1 text-xs text-amber-400/80">
                          Consider reaching out:
                        </p>
                        <div className="mt-2 flex flex-col gap-1 text-sm">
                          <a
                            href="tel:14416"
                            className="font-medium text-amber-300 underline underline-offset-2"
                          >
                            Tele-MANAS: 14416
                          </a>
                          <a
                            href="tel:9152987821"
                            className="font-medium text-amber-300 underline underline-offset-2"
                          >
                            iCall: 9152987821
                          </a>
                          <p className="text-xs text-amber-400/70">
                            Or speak to your college counselor
                          </p>
                        </div>
                      </div>
                      <button
                        onClick={() => setCrisisDismissed(true)}
                        className="shrink-0 text-sm text-amber-400/60 hover:text-amber-400"
                        aria-label="Dismiss"
                      >
                        ✕
                      </button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              <ParsedEntryView
                log={log}
                entries={entries}
                mentalState={mentalState}
                wellbeingInsight={wellbeingInsight}
                onEdit={() => setEditing(true)}
              />

              {/* Need support card — only visible in State 3 */}
              <button
                onClick={() => router.push('/coping')}
                className="flex w-full cursor-pointer items-center justify-between rounded-xl border border-indigo-500/30 bg-indigo-950/40 p-4 text-left transition-colors hover:border-indigo-400/50"
              >
                <div>
                  <p className="text-sm font-medium text-[var(--text-primary)]">
                    Take a breather 🌬️
                  </p>
                  <p className="mt-0.5 text-sm text-[var(--text-muted)]">
                    A few minutes can make a difference
                  </p>
                </div>
                <ArrowRight size={16} className="shrink-0 text-[var(--text-muted)]" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* ── Start New Day — subtle, only when an entry exists ─────────── */}
        {hasEntry && !isLoading && (
          <div className="mt-8 flex justify-center">
            <button
              onClick={() => setShowNewDayModal(true)}
              className="text-xs text-[var(--text-muted)] transition-colors hover:text-[var(--text-secondary)]"
            >
              Start New Day →
            </button>
          </div>
        )}
      </div>

      {/* ── Start New Day confirmation modal ──────────────────────────────── */}
      <AnimatePresence>
        {showNewDayModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4 backdrop-blur-sm"
            onClick={(e) => e.target === e.currentTarget && setShowNewDayModal(false)}
          >
            <motion.div
              initial={{ scale: 0.92, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.92, opacity: 0 }}
              transition={{ type: 'spring', stiffness: 400, damping: 30 }}
              className="w-full max-w-sm rounded-2xl border border-[var(--border)] bg-[var(--card)] p-6"
            >
              <h2 className="text-base font-semibold text-[var(--text-primary)]">
                Start a new day?
              </h2>
              <p className="mt-2 text-sm leading-relaxed text-[var(--text-muted)]">
                Starting a new day will close today&apos;s log. You won&apos;t
                be able to edit it after this. Ready to start fresh?
              </p>
              <div className="mt-5 flex gap-2">
                <button
                  onClick={() => setShowNewDayModal(false)}
                  className="flex-1 rounded-xl border border-[var(--border)] bg-[var(--card-elevated)] py-2.5 text-sm font-medium text-[var(--text-secondary)]"
                >
                  Not yet
                </button>
                <motion.button
                  onClick={handleConfirmNewDay}
                  disabled={startingNewDay}
                  whileTap={{ scale: 0.97 }}
                  className="flex-1 rounded-xl bg-[var(--accent)] py-2.5 text-sm font-semibold text-white disabled:opacity-60"
                >
                  {startingNewDay ? (
                    <span className="flex items-center justify-center gap-2">
                      <Loader2 size={14} className="animate-spin" />
                      Starting…
                    </span>
                  ) : (
                    'Start New Day'
                  )}
                </motion.button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}
